# mongo docker service
# author: zhujun
# date: 2018-06-11
version: '3.1'

services:
# docker run -d --name mongo -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=qwer1234 -p 27017:27017 -v /data1/mongo/db:/data/db mongo:3.6
# docker run -d --name mongo -p 27017:27017 -v /data1/mongo/db:/data/db mongo:3.6
  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwer1234
    volumes:
      - /data1/mongo/db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwer1234