server:
  port: 8618 #ui port

logging:
  level:
    com:
      zhujun:
        spider: DEBUG

spring:
  profiles:
    active: dev
  resources:
    static-locations: file:src/main/resources/ui/

spider:
  port: 8619
  mina:
    log-filter: false

  mongo:
    url: mongodb://root:qwer1234@42.123.99.34:27017/?authSource=admin&authMechanism=SCRAM-SHA-1

---
spring:
  profiles: dev

spider:
  mongo:
    url: mongodb://root:qwer1234@42.123.99.34:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
    master-db-name: spider_master_dev


---
spring:
  profiles: prod

  resources:
    static-locations: classpath:/ui/

spider:
  mina:
    log-filter: false

  mongo:
    url: mongodb://root:qwer1234@42.123.99.34:27017/?authSource=admin&authMechanism=SCRAM-SHA-1
    master-db-name: spider_master
